apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
  namespace: api-dev-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
        - name: privatepocacr01
          image: privatepocacr01.azurecr.io/productapi:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080