SERVICE_NAME: product-api
SERVICE_PORT: 80
TARGET_PORT: 8080
REPLICA_COUNT: 1
CONTAINER_NAME: sandboxazacrpoc01
IMAGE_NAME: sandboxazacrpoc01.azurecr.io/productapi:latest
IMAGE_PULL_POLICY: Always
IS_PAGINATION_ENABLED: true
PAGE_SIZE: 5