apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.SERVICE_NAME }}
  namespace: {{ .Values.NAMESPACE }}
spec:
  replicas: {{ .Values.REPLICA_COUNT }}
  selector:
    matchLabels:
      app: {{ .Values.SERVICE_NAME }}
  template:
    metadata:
      labels:
        app: {{ .Values.SERVICE_NAME }}
    spec:
      containers:
        - name: {{ .Values.CONTAINER_NAME }}
          image: {{ .Values.IMAGE_NAME }}
          imagePullPolicy: {{ .Values.IMAGE_PULL_POLICY }}
          ports:
          - containerPort: {{ .Values.TARGET_PORT }}
          envFrom:
            - configMapRef:
                name: {{ .Values.SERVICE_NAME }}-appsettings-config
          volumeMounts:
            - name: appsettings-config
              mountPath: /app/configmap
              readOnly: true
      volumes:
        - name: appsettings-config
          configMap:
            name: {{ .Values.SERVICE_NAME }}-appsettings-config