apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.SERVICE_NAME }}
  namespace: api-dev-01
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.SERVICE_PORT }}
      #targetPort: {{ .Values.TARGET_PORT }}
  selector:
    app: {{ .Values.SERVICE_NAME }}